# Generated by Django 5.2.17 on 2026-09-24 07:46

import content.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('contact', models.CharField(max_length=255, verbose_name='Телефон или e-mail')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(max_length=5000, verbose_name='Текст')),
                ('lang', models.CharField(default='ru', max_length=2, verbose_name='Язык')),
                ('consent', models.BooleanField(verbose_name='Согласие на обработку персональных данных')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('done', 'Обработано')], default='new', max_length=15, verbose_name='Статус')),
                ('staff_note', models.TextField(blank=True, verbose_name='Заметка сотрудника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kk', models.CharField(max_length=255, verbose_name='Название (қаз.)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (рус.)')),
                ('category', models.CharField(choices=[('charter', 'Устав'), ('gos', 'ГОСО'), ('rules', 'Типовые правила'), ('program', 'Образовательные программы'), ('schedule', 'Режим дня и расписание'), ('admission', 'Приём в детский сад'), ('contract', 'Договоры и заявления'), ('payment', 'Оплата'), ('menu', 'Меню'), ('nutrition', 'Организация питания'), ('report', 'Отчёты'), ('budget', 'Бюджет'), ('procurement', 'Закупки'), ('other', 'Прочее')], max_length=20, verbose_name='Категория')),
                ('language', models.CharField(choices=[('kk', 'Казахский'), ('ru', 'Русский'), ('both', 'Казахский и русский')], default='both', max_length=4, verbose_name='Язык документа')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), content.models.MaxSizeValidator(20)], verbose_name='Файл')),
                ('published_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['category', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('section', models.CharField(choices=[('parents', 'Родителям'), ('appeals', 'Обращения')], max_length=10, verbose_name='Раздел')),
                ('question_kk', models.CharField(max_length=500, verbose_name='Вопрос (қаз.)')),
                ('question_ru', models.CharField(max_length=500, verbose_name='Вопрос (рус.)')),
                ('answer_kk', models.TextField(verbose_name='Ответ (қаз.)')),
                ('answer_ru', models.TextField(verbose_name='Ответ (рус.)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Частые вопросы',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('name_kk', models.CharField(max_length=120, verbose_name='Название (қаз.)')),
                ('name_ru', models.CharField(max_length=120, verbose_name='Название (рус.)')),
                ('age_kk', models.CharField(help_text='Например: 3–4 жас', max_length=60, verbose_name='Возраст (қаз.)')),
                ('age_ru', models.CharField(help_text='Например: 3–4 года', max_length=60, verbose_name='Возраст (рус.)')),
                ('language', models.CharField(choices=[('kk', 'Казахский'), ('ru', 'Русский'), ('both', 'Казахский и русский')], default='kk', max_length=4, verbose_name='Язык обучения')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('news', 'Новость'), ('announcement', 'Объявление'), ('event', 'Мероприятие')], default='news', max_length=15, verbose_name='Тип')),
                ('title_kk', models.CharField(max_length=255, verbose_name='Заголовок (қаз.)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (рус.)')),
                ('summary_kk', models.CharField(blank=True, max_length=300, verbose_name='Кратко (қаз.)')),
                ('summary_ru', models.CharField(blank=True, max_length=300, verbose_name='Кратко (рус.)')),
                ('body_kk', models.TextField(blank=True, verbose_name='Текст (қаз.)')),
                ('body_ru', models.TextField(blank=True, verbose_name='Текст (рус.)')),
                ('cover', models.ImageField(blank=True, upload_to='news/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), content.models.MaxSizeValidator(10)], verbose_name='Обложка')),
                ('cover_alt_kk', models.CharField(blank=True, max_length=255, verbose_name='Описание обложки для незрячих (қаз.)')),
                ('cover_alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Описание обложки для незрячих (рус.)')),
                ('cover_consent', models.BooleanField(default=False, verbose_name='Подтверждаю: на фото нет детей ИЛИ есть письменное согласие родителей (законных представителей)')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата мероприятия')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость / объявление',
                'verbose_name_plural': 'Новости и объявления',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Код раздела')),
                ('title_kk', models.CharField(max_length=255, verbose_name='Заголовок (қаз.)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (рус.)')),
                ('body_kk', models.TextField(blank=True, verbose_name='Текст (қаз.)')),
                ('body_ru', models.TextField(blank=True, verbose_name='Текст (рус.)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Текст раздела',
                'verbose_name_plural': 'Тексты разделов',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('kind', models.CharField(choices=[('leader', 'Руководство'), ('teacher', 'Педагог / специалист')], max_length=10, verbose_name='Раздел')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position_kk', models.CharField(max_length=255, verbose_name='Должность (қаз.)')),
                ('position_ru', models.CharField(max_length=255, verbose_name='Должность (рус.)')),
                ('education_kk', models.CharField(blank=True, max_length=500, verbose_name='Образование (қаз.)')),
                ('education_ru', models.CharField(blank=True, max_length=500, verbose_name='Образование (рус.)')),
                ('qualification_kk', models.CharField(blank=True, max_length=255, verbose_name='Квалификация / категория (қаз.)')),
                ('qualification_ru', models.CharField(blank=True, max_length=255, verbose_name='Квалификация / категория (рус.)')),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Педагогический стаж, лет')),
                ('reception_kk', models.CharField(blank=True, max_length=255, verbose_name='Часы приёма (қаз.)')),
                ('reception_ru', models.CharField(blank=True, max_length=255, verbose_name='Часы приёма (рус.)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Рабочий телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Рабочий e-mail')),
                ('photo', models.ImageField(blank=True, upload_to='people/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), content.models.MaxSizeValidator(10)], verbose_name='Фото')),
                ('show_photo', models.BooleanField(default=False, help_text='Только если сотрудник дал согласие на публикацию фото', verbose_name='Показывать фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Сотрудник на сайте',
                'verbose_name_plural': 'Сотрудники на сайте',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (қаз.)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус.)')),
                ('tagline_kk', models.CharField(blank=True, max_length=255, verbose_name='Короткое описание (қаз.)')),
                ('tagline_ru', models.CharField(blank=True, max_length=255, verbose_name='Короткое описание (рус.)')),
                ('logo', models.ImageField(blank=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), content.models.MaxSizeValidator(10)], verbose_name='Логотип')),
                ('address_kk', models.CharField(blank=True, max_length=255, verbose_name='Адрес (қаз.)')),
                ('address_ru', models.CharField(blank=True, max_length=255, verbose_name='Адрес (рус.)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('work_hours_kk', models.CharField(blank=True, help_text='Например: Дүйсенбі–Жұма, 07:30–19:00', max_length=255, verbose_name='Режим работы, текстом (қаз.)')),
                ('work_hours_ru', models.CharField(blank=True, help_text='Например: Пн–Пт, 07:30–19:00', max_length=255, verbose_name='Режим работы, текстом (рус.)')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Открытие')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Закрытие')),
                ('open_weekdays', models.CharField(default='12345', help_text='Цифры дней: 1 — понедельник … 7 — воскресенье', max_length=7, verbose_name='Рабочие дни')),
                ('founder_kk', models.TextField(blank=True, verbose_name='Учредитель (қаз.)')),
                ('founder_ru', models.TextField(blank=True, verbose_name='Учредитель (рус.)')),
                ('history_kk', models.TextField(blank=True, verbose_name='История (қаз.)')),
                ('history_ru', models.TextField(blank=True, verbose_name='История (рус.)')),
                ('reception_kk', models.TextField(blank=True, verbose_name='График приёма граждан (қаз.)')),
                ('reception_ru', models.TextField(blank=True, verbose_name='График приёма граждан (рус.)')),
                ('map_embed_url', models.URLField(blank=True, help_text='Ссылка «для встраивания» из Яндекс.Карт, 2ГИС или Google Maps', verbose_name='Ссылка на карту для встраивания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('title_kk', models.CharField(max_length=255, verbose_name='Должность (қаз.)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Должность (рус.)')),
                ('requirements_kk', models.TextField(verbose_name='Требования (қаз.)')),
                ('requirements_ru', models.TextField(verbose_name='Требования (рус.)')),
                ('conditions_kk', models.TextField(blank=True, verbose_name='Условия (қаз.)')),
                ('conditions_ru', models.TextField(blank=True, verbose_name='Условия (рус.)')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакт для связи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальна')),
                ('published_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('image', models.ImageField(upload_to='news/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), content.models.MaxSizeValidator(10)], verbose_name='Фото')),
                ('alt_kk', models.CharField(max_length=255, verbose_name='Описание для незрячих (қаз.)')),
                ('alt_ru', models.CharField(max_length=255, verbose_name='Описание для незрячих (рус.)')),
                ('consent', models.BooleanField(default=False, verbose_name='Подтверждаю: на фото нет детей ИЛИ есть письменное согласие родителей (законных представителей)')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.news')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
