# Generated by Django 5.2.17 on 2026-09-24 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_pid', models.BigIntegerField(db_index=True)),
                ('child_iin', models.CharField(blank=True, max_length=20)),
                ('child_fio', models.CharField(blank=True, max_length=200)),
                ('fio', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=160)),
                ('iin', models.CharField(blank=True, max_length=20)),
                ('relation', models.CharField(blank=True, max_length=160)),
                ('raw', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Родитель / опекун',
                'verbose_name_plural': 'Родители / опекуны',
                'ordering': ['child_fio', 'fio'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('p_id', models.BigIntegerField()),
                ('child_fio', models.CharField(max_length=200)),
                ('group_name', models.CharField(blank=True, max_length=120)),
                ('day_num', models.IntegerField()),
                ('old_status', models.CharField(blank=True, max_length=80)),
                ('new_status', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Изменение табеля',
                'verbose_name_plural': 'Журнал изменений табеля',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, default='', max_length=7)),
                ('p_id', models.BigIntegerField(db_index=True)),
                ('iin', models.CharField(blank=True, max_length=20)),
                ('fio', models.CharField(max_length=200)),
                ('age', models.CharField(blank=True, max_length=40)),
                ('group_id', models.BigIntegerField(db_index=True)),
                ('group_name', models.CharField(blank=True, max_length=120)),
                ('tmsh_id', models.BigIntegerField(blank=True, null=True)),
                ('days_json', models.TextField(default='{}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ребёнок в табеле',
                'verbose_name_plural': 'Табель: дети по месяцам',
                'ordering': ['group_name', 'fio'],
                'unique_together': {('month', 'p_id')},
            },
        ),
        migrations.CreateModel(
            name='ParentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('iin', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('last_owed', models.FloatField(default=-1)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подписка родителя',
                'verbose_name_plural': 'Подписки родителей (напоминания)',
                'unique_together': {('chat_id', 'iin')},
            },
        ),
        migrations.CreateModel(
            name='PaymentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('iin', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('paid_at', models.CharField(blank=True, max_length=60)),
                ('payer_fio', models.CharField(blank=True, max_length=200)),
                ('month', models.CharField(max_length=7)),
                ('purpose', models.CharField(default='Оплата за месяц', max_length=120)),
                ('raw', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='payments.childrecord')),
            ],
            options={
                'verbose_name': 'Квитанция из бота',
                'verbose_name_plural': 'Квитанции из бота',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_payment', models.FloatField(default=0)),
                ('monthly_payment', models.FloatField(default=51000)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payments.childrecord')),
            ],
            options={
                'verbose_name': 'Оплата за месяц',
                'verbose_name_plural': 'Оплаты за месяц',
            },
        ),
    ]
