# Generated by Django 5.2.17 on 2026-09-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_guardian_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='relation',
        ),
    ]
