# Generated by Django 5.2.17 on 2026-09-26 14:55

from django.db import migrations, models


def fill_children(apps, schema_editor):
    """Воспитанники из уже загруженного табеля: данные — из последнего месяца ребёнка."""
    ChildRecord = apps.get_model("payments", "ChildRecord")
    Child = apps.get_model("payments", "Child")
    latest = {}
    for rec in ChildRecord.objects.order_by("month"):
        latest[rec.p_id] = rec
    Child.objects.bulk_create(
        [Child(p_id=r.p_id, iin=r.iin, fio=r.fio, group_name=r.group_name, last_month=r.month) for r in latest.values()]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_guardian_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.BigIntegerField(unique=True, verbose_name='ID в табеле')),
                ('iin', models.CharField(blank=True, max_length=20, verbose_name='ИИН')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('group_name', models.CharField(blank=True, max_length=120, verbose_name='Группа')),
                ('last_month', models.CharField(blank=True, max_length=7, verbose_name='Последний месяц в табеле')),
                ('is_active', models.BooleanField(default=True, help_text='У выбывших снимите галочку: в журналах их не будет в списке детей, записи останутся.', verbose_name='Посещает детский сад')),
            ],
            options={
                'verbose_name': 'Воспитанник',
                'verbose_name_plural': 'Воспитанники',
                'ordering': ['fio'],
            },
        ),
        migrations.RunPython(fill_children, migrations.RunPython.noop),
    ]
