# Generated by Django 5.2.17 on 2026-09-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_child'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentLink',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.AlterModelOptions(
            name='paymentimport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Квитанция (архив)', 'verbose_name_plural': 'Квитанции (архив)'},
        ),
    ]
