# Generated by Django 5.2.17 on 2026-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_telegram_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Домашний адрес'),
        ),
        migrations.AddField(
            model_name='child',
            name='contract_date',
            field=models.DateField(blank=True, help_text='Она же дата зачисления в медицинских журналах.', null=True, verbose_name='Дата подписания договора'),
        ),
        migrations.AddField(
            model_name='child',
            name='contract_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Отец'), (2, 'Мать')], null=True, verbose_name='Кем приходится'),
        ),
    ]
