# Generated by Django 5.2.18 on 2026-10-07 13:11

from django.db import migrations, models
from django.utils import timezone

OLD_DEFAULT_MONTHLY = 51000  # ежемесячная оплата по умолчанию до этой миграции


def new_defaults_from_this_month(apps, schema_editor):
    """Новые суммы по умолчанию (51 000 многодетной семье, 60 000 остальным) — с текущего месяца.
    В прошлых месяцах остаётся прежняя сумма, чтобы долги задним числом не изменились;
    в текущем и следующих прежняя сумма по умолчанию снова становится «по умолчанию»."""
    ChildRecord = apps.get_model('payments', 'ChildRecord')
    PaymentInfo = apps.get_model('payments', 'PaymentInfo')
    current = timezone.localdate().strftime('%Y-%m')
    PaymentInfo.objects.bulk_create(
        [PaymentInfo(child=rec, monthly_payment=OLD_DEFAULT_MONTHLY)
         for rec in ChildRecord.objects.filter(month__lt=current, payment__isnull=True)],
        batch_size=500,
    )
    PaymentInfo.objects.filter(child__month__gte=current, monthly_payment=OLD_DEFAULT_MONTHLY).update(monthly_payment=None)


def back_to_old_default(apps, schema_editor):
    PaymentInfo = apps.get_model('payments', 'PaymentInfo')
    PaymentInfo.objects.filter(monthly_payment=None).update(monthly_payment=OLD_DEFAULT_MONTHLY)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_child_contract_guardian_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='large_family',
            field=models.BooleanField(blank=True, choices=[(None, 'Определять по родителям'), (True, 'Да'), (False, 'Нет')], help_text='По родителям — многодетная, если в табеле за месяц есть ещё ребёнок того же родителя (по ИИН родителя из e-orda). «Да» — например, если остальные дети в сад не ходят.', null=True, verbose_name='Многодетная семья'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('online', 'Онлайн')], max_length=10, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='monthly_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(new_defaults_from_this_month, back_to_old_default),
    ]
