# Generated by Django 5.2.18 on 2026-10-07 17:04

from django.db import migrations, models


def manual_only(apps, schema_editor):
    """Многодетных больше не определяем по родителям: остаются только отмеченные вручную «Да»."""
    Child = apps.get_model('payments', 'Child')
    Child.objects.filter(large_family=None).update(large_family=False)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_family_payment_method'),
    ]

    operations = [
        migrations.RunPython(manual_only, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='child',
            name='large_family',
            field=models.BooleanField(default=False, help_text='Ставится вручную. Ежемесячная оплата по умолчанию — 51 000 ₸. Отметка остаётся после очистки месяца и новой загрузки табеля.', verbose_name='Многодетная семья'),
        ),
    ]
