# Generated by Django 5.2.17 on 2026-09-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medjournal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=40, unique=True, verbose_name='Журнал')),
                ('started', models.DateField(blank=True, null=True, verbose_name='Начат')),
                ('finished', models.DateField(blank=True, null=True, verbose_name='Окончен')),
            ],
            options={
                'verbose_name': 'Даты ведения журнала',
                'verbose_name_plural': 'Даты ведения журналов',
            },
        ),
    ]
